services:
   app:
     build: .
     command: python manage.py runserver 0.0.0.0:3000
     restart: unless-stopped
    #  depends_on:
    #    - database
     volumes:
       - $PWD:/app
    #  environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
     ports:                                                 
       - 5000:5000 

  #  database:
  #    image: postgres:13
  #    restart: unless-stopped
  #    environment:
  #      - POSTGRES_PASSWORD=postgres
  #    volumes:
  #      - ./postgres-data:/var/lib/postgresql/data
  #    ports:
  #      - 5432:5432