services:
   app:
     build: .
     command: python manage.py runserver 0.0.0.0:5000
     restart: unless-stopped
    #  depends_on:
    #    - database
     volumes:
       - $PWD:/app
    #  env_file:
    #    - app.env
     ports:                                                 
       - 5000:5000 

  #  database:
  #    image: postgres:13
  #    restart: unless-stopped
  #    environment:
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_PASSWORD=example_password
  #      - POSTGRES_DB=example_db
  #    volumes:
  #      - ./postgres-data:/var/lib/postgresql/data
  #    ports:
  #      - 5432:5432